"""Step 14 - assemble the manuscript sections into a single document."""
from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from config import LOGS, ROOT, Tee

MS = ROOT / "manuscript"
log = Tee(LOGS / "14_assemble.txt")

TITLE = """# Knowing When Not to Assign: Uncertainty-Aware Open-Set Machine Learning for pXRF-Based Archaeological Ceramic Provenance

**Target journal:** *Archaeological and Anthropological Sciences* (Original Paper)

**Author:** Kun Xiang

**Affiliation:** Research Center for Machine Learning and Environmental Decision Science, China Three Gorges University, Yichang, China

**Corresponding author:** Kun Xiang, xiangkun@ctgu.edu.cn

**Keywords:** archaeological ceramics; provenance analysis; portable X-ray
fluorescence; machine learning; open-set recognition; uncertainty quantification

---

> Manuscript status: every number in the Results is generated by the pipeline
> in `code/` and traceable to `outputs/tables/` through
> `outputs/logs/RESULTS_DIGEST.md`. The submission package includes numbered
> supplementary tables and figures plus a reproducibility archive. Continuous
> line numbering is applied in the typeset manuscript.

---

"""

ORDER = [
    ("abstract.md", None),
    ("introduction.md", None),
    ("methods.md", None),
    ("results.md", None),
    ("discussion.md", None),
    ("statements.md", None),
    ("references.md", None),
    ("figure_legends.md", None),
]

parts = [TITLE]
for name, _ in ORDER:
    p = MS / name
    if p.exists():
        parts.append(p.read_text(encoding="utf-8").rstrip() + "\n\n---\n\n")
        log("included {:20s} ({:,} chars)".format(name, len(p.read_text(encoding='utf-8'))))
    else:
        log("MISSING  {}".format(name))

out = MS / "manuscript_full.md"
out.write_text("".join(parts), encoding="utf-8")
words = len("".join(parts).split())
log("")
log("Wrote {} ({:,} words)".format(out, words))
log.close()
